<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>3aadd854-fe64-4b13-8392-e90ec5a7433e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.5.4" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.5.4" />
    <PackageReference Include="Scalar.Aspire" Version="0.11.24" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gateway\Gateway.csproj" />
    <ProjectReference Include="..\ParkingLot.Api\ParkingLot.Api.csproj" />
  </ItemGroup>

</Project>
