// This file is auto-generated by @hey-api/openapi-ts

export type {
  ClientOptions,
  GetParkingLotData,
  GetParkingLotResponse,
  GetParkingLotResponses,
  ItemAddedData,
  ItemAddedResponse,
  ItemAddedResponses,
  Note,
  ParkingLotCreateItem,
  ParkingLotDetailsItem,
  ParkingLotSummaryItem,
  PostParkingLotData,
  PostParkingLotResponse,
  PostParkingLotResponses,
} from './types.gen';
