// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zNote = z.object({
  id: z.uuid().optional(),
  content: z.string().optional(),
  added: z.iso.datetime().optional(),
});

export const zParkingLotCreateItem = z.object({
  title: z.string().min(5).max(100),
  description: z.string().max(500).optional(),
});

export const zParkingLotDetailsItem = z.object({
  id: z.uuid().optional(),
  title: z.string().optional(),
  description: z.string().optional(),
  created: z.iso.datetime().optional(),
  notes: z.array(zNote).optional(),
});

export const zParkingLotSummaryItem = z.object({
  id: z.uuid().optional(),
  title: z.string().optional(),
  description: z.string().optional(),
  created: z.iso.datetime().optional(),
});

/**
 * OK
 */
export const zGetParkingLotResponse = z.array(zParkingLotSummaryItem);

export const zPostParkingLotBody = zParkingLotCreateItem;

/**
 * OK
 */
export const zPostParkingLotResponse = zParkingLotDetailsItem;

export const zItemAddedPath = z.object({
  id: z.uuid(),
});

/**
 * OK
 */
export const zItemAddedResponse = zParkingLotDetailsItem;
