// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'https://parkinglot-api/' | (string & {});
};

export type Note = {
  id: string;
  content?: string;
  added?: string;
};

export type ParkingLotCreateItem = {
  title: string;
  description?: string;
};

export type ParkingLotDetailsItem = {
  id?: string;
  title?: string;
  description?: string;
  created?: string;
  notes?: Note[];
};

export type ParkingLotSummaryItem = {
  id?: string;
  title?: string;
  description?: string;
  created?: string;
};

export type GetParkingLotData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/parking-lot';
};

export type GetParkingLotResponses = {
  /**
   * OK
   */
  200: ParkingLotSummaryItem[];
};

export type GetParkingLotResponse = GetParkingLotResponses[keyof GetParkingLotResponses];

export type PostParkingLotData = {
  body: ParkingLotCreateItem;
  path?: never;
  query?: never;
  url: '/parking-lot';
};

export type PostParkingLotResponses = {
  /**
   * OK
   */
  200: ParkingLotDetailsItem;
};

export type PostParkingLotResponse = PostParkingLotResponses[keyof PostParkingLotResponses];

export type ItemAddedData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/parking-lot/{id}';
};

export type ItemAddedResponses = {
  /**
   * OK
   */
  200: ParkingLotDetailsItem;
};

export type ItemAddedResponse = ItemAddedResponses[keyof ItemAddedResponses];
