@Links.Api_HostAddress = https://localhost:1337

# Add A Link To Share

POST {{Links.Api_HostAddress}}/links
Content-Type: application/json 

{
  "title": "Hypertheory Labs",
  "url": "your mom wears combat boots"
}

###

GET {{Links.Api_HostAddress}}/links 

# Get a List of Links
###
